# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FeedbackP2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FeedbackP2.proto',
  package='p2_v1',
  syntax='proto2',
  serialized_options=b'\n\021com.al.cc.java.p2B\017FeedBackSchemas',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x46\x65\x65\x64\x62\x61\x63kP2.proto\x12\x05p2_v1\"\xd7\x01\n\x08\x46\x65\x65\x64\x62\x61\x63k\x12\x1c\n\rlife_cycle_id\x18\x01 \x01(\x03:\x05-9999\x12\x13\n\x04name\x18\x02 \x01(\t:\x05-9999\x12\x14\n\x05gc_id\x18\x03 \x01(\t:\x05-9999\x12#\n\x06gender\x18\x04 \x01(\x0e\x32\r.p2_v1.Gender:\x04MALE\x12\x11\n\x02id\x18\x05 \x01(\t:\x05-9999\x12\x36\n\x0eparkingLotType\x18\x06 \x01(\x0e\x32\x15.p2_v1.ParkingLotType:\x07OUTSIDE\x12\x12\n\x04\x65Pay\x18\x07 \x01(\x08:\x04true*.\n\x0eParkingLotType\x12\x0f\n\x0bUNDERGROUND\x10\x00\x12\x0b\n\x07OUTSIDE\x10\x01*\x1e\n\x06Gender\x12\n\n\x06\x46\x45MALE\x10\x00\x12\x08\n\x04MALE\x10\x01\x42$\n\x11\x63om.al.cc.java.p2B\x0f\x46\x65\x65\x64\x42\x61\x63kSchemas'
)

_PARKINGLOTTYPE = _descriptor.EnumDescriptor(
  name='ParkingLotType',
  full_name='p2_v1.ParkingLotType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDERGROUND', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OUTSIDE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=245,
  serialized_end=291,
)
_sym_db.RegisterEnumDescriptor(_PARKINGLOTTYPE)

ParkingLotType = enum_type_wrapper.EnumTypeWrapper(_PARKINGLOTTYPE)
_GENDER = _descriptor.EnumDescriptor(
  name='Gender',
  full_name='p2_v1.Gender',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FEMALE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MALE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=293,
  serialized_end=323,
)
_sym_db.RegisterEnumDescriptor(_GENDER)

Gender = enum_type_wrapper.EnumTypeWrapper(_GENDER)
UNDERGROUND = 0
OUTSIDE = 1
FEMALE = 0
MALE = 1



_FEEDBACK = _descriptor.Descriptor(
  name='Feedback',
  full_name='p2_v1.Feedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='life_cycle_id', full_name='p2_v1.Feedback.life_cycle_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=-9999,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='p2_v1.Feedback.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"-9999".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gc_id', full_name='p2_v1.Feedback.gc_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"-9999".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gender', full_name='p2_v1.Feedback.gender', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='p2_v1.Feedback.id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"-9999".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parkingLotType', full_name='p2_v1.Feedback.parkingLotType', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ePay', full_name='p2_v1.Feedback.ePay', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=243,
)

_FEEDBACK.fields_by_name['gender'].enum_type = _GENDER
_FEEDBACK.fields_by_name['parkingLotType'].enum_type = _PARKINGLOTTYPE
DESCRIPTOR.message_types_by_name['Feedback'] = _FEEDBACK
DESCRIPTOR.enum_types_by_name['ParkingLotType'] = _PARKINGLOTTYPE
DESCRIPTOR.enum_types_by_name['Gender'] = _GENDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Feedback = _reflection.GeneratedProtocolMessageType('Feedback', (_message.Message,), {
  'DESCRIPTOR' : _FEEDBACK,
  '__module__' : 'FeedbackP2_pb2'
  # @@protoc_insertion_point(class_scope:p2_v1.Feedback)
  })
_sym_db.RegisterMessage(Feedback)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
